name: Publish Extension
# This workflow is triggered on pushes to the repository.
on: [tags]

jobs:
  publish:
    # Job name is Greeting
    name: Publish
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rm -Rf .git*
      - run: rm -Rf *.sketch
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./extension.zip ./
      - uses: Klemensas/chrome-extension-upload-action@$VERSION
        with:
          refresh-token: $REFRESH_TOKEN
          client-id: $CLIENT_ID
          client-secret: $CLIENT_SECRET
          file-name: './extension.zip'
          app-id: $APP_ID
          publish: true
