name: Publish Extension
# This workflow is triggered on pushes to the repository.
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    # Job name is Greeting
    name: Publish
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - run: rm -Rf .git*
      - run: rm -Rf *.sketch
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./extension.zip ./
      - uses: Klemensas/chrome-extension-upload-action@$VERSION
        with:
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          file-name: './extension.zip'
          app-id: ${{ secrets.APP_ID }}
          publish: true
